CANONICAL_FEATURES = [
    "dst_port",
    "protocol",
    "Timestamp",
    "flow_duration",
    "tot_fwd_pkts",
    "tot_bwd_pkts",
    "totlen_fwd_pkts",
    "totlen_bwd_pkts",
    "fwd_pkt_len_max",
    "fwd_pkt_len_min",
    "fwd_pkt_len_mean",
    "fwd_pkt_len_std",
    "bwd_pkt_len_max",
    "bwd_pkt_len_min",
    "bwd_pkt_len_mean",
    "bwd_pkt_len_std",
    "flow_bytes_per_sec",
    "flow_pkts_per_sec",
    "flow_iat_mean",
    "flow_iat_std",
    "flow_iat_max",
    "flow_iat_min",
    "fwd_iat_tot",
    "fwd_iat_mean",
    "fwd_iat_std",
    "fwd_iat_max",
    "fwd_iat_min",
    "bwd_iat_tot",
    "bwd_iat_mean",
    "bwd_iat_std",
    "bwd_iat_max",
    "bwd_iat_min",
    "fwd_psh_flags",
    "bwd_psh_flags",
    "fwd_urg_flags",
    "bwd_urg_flags",
    "fwd_header_len",
    "bwd_header_len",
    "fwd_pkts_per_sec",
    "bwd_pkts_per_sec",
    "pkt_len_min",
    "pkt_len_max",
    "pkt_len_mean",
    "pkt_len_std",
    "pkt_len_var",
    "fin_flag_cnt",
    "syn_flag_cnt",
    "rst_flag_cnt",
    "psh_flag_cnt",
    "ack_flag_cnt",
    "urg_flag_cnt",
    "cwe_flag_count",
    "ece_flag_cnt",
    "down_up_ratio",
    "pkt_size_avg",
    "fwd_seg_size_avg",
    "bwd_seg_size_avg",
    "fwd_byts_b_avg",
    "fwd_pkts_b_avg",
    "fwd_blk_rate_avg",
    "bwd_byts_b_avg",
    "bwd_pkts_b_avg",
    "bwd_blk_rate_avg",
    "subflow_fwd_pkts",
    "subflow_fwd_byts",
    "subflow_bwd_pkts",
    "subflow_bwd_byts",
    "init_fwd_win_byts",
    "init_bwd_win_byts",
    "fwd_act_data_pkts",
    "fwd_seg_size_min",
    "active_mean",
    "active_std",
    "active_max",
    "active_min",
    "idle_mean",
    "idle_std",
    "idle_max",
    "idle_min",
    "label"
]

DATASET_COLUMN_MAPPINGS = {
    # CIC-IDS2018 conventions
    "cic": {
        "Dst Port": "dst_port",
        "Protocol": "protocol",
        "Timestamp": "Timestamp",
        "Flow Duration": "flow_duration",
        "Tot Fwd Pkts": "tot_fwd_pkts",
        "Tot Bwd Pkts": "tot_bwd_pkts",
        "TotLen Fwd Pkts": "totlen_fwd_pkts",
        "TotLen Bwd Pkts": "totlen_bwd_pkts",
        "Fwd Pkt Len Max": "fwd_pkt_len_max",
        "Fwd Pkt Len Min": "fwd_pkt_len_min",
        "Fwd Pkt Len Mean": "fwd_pkt_len_mean",
        "Fwd Pkt Len Std": "fwd_pkt_len_std",
        "Bwd Pkt Len Max": "bwd_pkt_len_max",
        "Bwd Pkt Len Min": "bwd_pkt_len_min",
        "Bwd Pkt Len Mean": "bwd_pkt_len_mean",
        "Bwd Pkt Len Std": "bwd_pkt_len_std",
        "Flow Byts/s": "flow_bytes_per_sec",
        "Flow Pkts/s": "flow_pkts_per_sec",
        "Flow IAT Mean": "flow_iat_mean",
        "Flow IAT Std": "flow_iat_std",
        "Flow IAT Max": "flow_iat_max",
        "Flow IAT Min": "flow_iat_min",
        "Fwd IAT Tot": "fwd_iat_tot",
        "Fwd IAT Mean": "fwd_iat_mean",
        "Fwd IAT Std": "fwd_iat_std",
        "Fwd IAT Max": "fwd_iat_max",
        "Fwd IAT Min": "fwd_iat_min",
        "Bwd IAT Tot": "bwd_iat_tot",
        "Bwd IAT Mean": "bwd_iat_mean",
        "Bwd IAT Std": "bwd_iat_std",
        "Bwd IAT Max": "bwd_iat_max",
        "Bwd IAT Min": "bwd_iat_min",
        "Fwd PSH Flags": "fwd_psh_flags",
        "Bwd PSH Flags": "bwd_psh_flags",
        "Fwd URG Flags": "fwd_urg_flags",
        "Bwd URG Flags": "bwd_urg_flags",
        "Fwd Header Len": "fwd_header_len",
        "Bwd Header Len": "bwd_header_len",
        "Fwd Pkts/s": "fwd_pkts_per_sec",
        "Bwd Pkts/s": "bwd_pkts_per_sec",
        "Pkt Len Min": "pkt_len_min",
        "Pkt Len Max": "pkt_len_max",
        "Pkt Len Mean": "pkt_len_mean",
        "Pkt Len Std": "pkt_len_std",
        "Pkt Len Var": "pkt_len_var",
        "FIN Flag Cnt": "fin_flag_cnt",
        "SYN Flag Cnt": "syn_flag_cnt",
        "RST Flag Cnt": "rst_flag_cnt",
        "PSH Flag Cnt": "psh_flag_cnt",
        "ACK Flag Cnt": "ack_flag_cnt",
        "URG Flag Cnt": "urg_flag_cnt",
        "CWE Flag Count": "cwe_flag_count",
        "ECE Flag Cnt": "ece_flag_cnt",
        "Down/Up Ratio": "down_up_ratio",
        "Pkt Size Avg": "pkt_size_avg",
        "Fwd Seg Size Avg": "fwd_seg_size_avg",
        "Bwd Seg Size Avg": "bwd_seg_size_avg",
        "Fwd Byts/b Avg": "fwd_byts_b_avg",
        "Fwd Pkts/b Avg": "fwd_pkts_b_avg",
        "Fwd Blk Rate Avg": "fwd_blk_rate_avg",
        "Bwd Byts/b Avg": "bwd_byts_b_avg",
        "Bwd Pkts/b Avg": "bwd_pkts_b_avg",
        "Bwd Blk Rate Avg": "bwd_blk_rate_avg",
        "Subflow Fwd Pkts": "subflow_fwd_pkts",
        "Subflow Fwd Byts": "subflow_fwd_byts",
        "Subflow Bwd Pkts": "subflow_bwd_pkts",
        "Subflow Bwd Byts": "subflow_bwd_byts",
        "Init Fwd Win Byts": "init_fwd_win_byts",
        "Init Bwd Win Byts": "init_bwd_win_byts",
        "Fwd Act Data Pkts": "fwd_act_data_pkts",
        "Fwd Seg Size Min": "fwd_seg_size_min",
        "Active Mean": "active_mean",
        "Active Std": "active_std",
        "Active Max": "active_max",
        "Active Min": "active_min",
        "Idle Mean": "idle_mean",
        "Idle Std": "idle_std",
        "Idle Max": "idle_max",
        "Idle Min": "idle_min",
        "Label": "label"
    },
    # UNSW-NB15 conventions
    "unsw": {
        "dur": "flow_duration",
        "spkts": "tot_fwd_pkts",
        "dpkts": "tot_bwd_pkts",
        "sbytes": "totlen_fwd_pkts",
        "dbytes": "totlen_bwd_pkts",
        "smeansz": "fwd_pkt_len_mean",
        "sinpkt": "flow_iat_mean",
        "rate": "flow_pkts_per_sec",
        "attack_cat": "label"
    }
}